language: minimal
sudo: required
services:
  - docker

before_install:
  - docker build -t trahomoto/react-ci -f Dockerfile.dev .

script:
  - docker run trahomoto/react-ci npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "react-ci"
  env: "ReactCi-env"
  bucket_name: "elasticbeanstalk-us-east-2-222263910670"
  bucket_path: "react-ci"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"